### ISSUE TITLE
Use font-smoothing on Button component

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#102]
Add `-webkit-font-smoothing: antialiased` to the Button component per discussion with @odmln 

See https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth

**Comment by hakimelek** [comment]
Should we actually add that to the [Base Component](https://github.com/pricelinelabs/design-system/blob/master/src/ThemeProvider.js#L13 ) in the `ThemeProvider`?
