### ISSUE TITLE
Section Tag Support By Container Component

### ISSUE THREAD

**Issue by BeniCheni** [pricelinelabs/design-system#114]
The following proposed pseudo code supports the `<section>` tag:
```
<Container.sec>
  ...
</Container.sec>
```

**Comment by byrekt** [comment]
I'd probably opt for something like this:
`tagName: PropTypes.oneOf(['div', 'section', '...any others'])`

and then in the render just have something like
`cont Tag = this.props.tagName || 'div'
  return (
   <Tag>
     {this.props.children}
   </Tag>
  ) 
`

But that's just my personal preference.

**Comment by BeniCheni** [comment]
@byrekt , I can see the flexibility with `tagName` prop to support many tags. I wrote the pseudo code with the thought to follow the existing dot-notation pattern in other components, i.e. `<Text.span>`:
https://github.com/pricelinelabs/design-system/blob/master/src/Text.js#L66

But I am happy to explore the `tagName` prop support approach.

@jxnblk et al, thoughts on ☝️?

**Comment by jxnblk** [comment]
The [`is` prop in Rebass](https://github.com/jxnblk/rebass#is-prop) is one of the reasons styled-components added `.withComponent` to the v2 API. For things like this, I would rather keep a separation of layout components (divs with styles) and other semantic markup. I don't see a compelling reason why someone using the design system couldn't use `Container.withComponent('section')` if they wanted (which is fewer custom APIs to learn) or just use composition, e.g.:

```jsx
<section id='about'>
  <Container>
    {this.props.children}
  </Container>
</section>
```

**Comment by BeniCheni** [comment]
Cool, @jxnblk. `<section>` wrapper outside of `<Container` would solve this use case. ✌️
