### ISSUE TITLE
Warning when use space in Icon 

### ISSUE THREAD

**Issue by Degron** [pricelinelabs/design-system#120]
![screen shot 2017-10-25 at 5 13 25 pm](https://user-images.githubusercontent.com/14366048/32026097-ccadb298-b9b0-11e7-975c-c21684e61760.png)

**Comment by jxnblk** [comment]
This is a long-standing issue with the styled-components library – they *still* don't have an elegant solution for blacklisting/whitelisting style props, but once they do, we will take advantage of it

See this for more https://github.com/styled-components/styled-components/issues/439

**Comment by jxnblk** [comment]
Think this is fixed, but feel free to reopen if not
