### ISSUE TITLE
Box `align` prop conflicts with Flex `align`

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#136]

**Comment by protoEvangelion** [comment]
I was getting an error `Received true for non-boolean attribute wrap`

and did this to solve it:

```js
import { omit } from 'lodash'

const Box = styled(props => <div {...omit(props, ['wrap'])} />)`
  ${space} ${width} ${color} ${align};
`
```

Maybe just adding 'align' to the omit array can solve this ;)

**Comment by protoEvangelion** [comment]
Hmmm, upon more thought it would probably just strip the `align` prop which it receives and not help at all :(
