### ISSUE TITLE
Add readable aliases for paddings and margins

### ISSUE THREAD

**Issue by hakimelek** [pricelinelabs/design-system#138]
I have heard many times that using `p` and `m` from [spaces](https://github.com/jxnblk/styled-system#space-responsive) is a bit confusing to use and is not very readable. The props from spaces include: 

- m: margin
- mt: margin-top
- mr: margin-right
- mb: margin-bottom
- ml: margin-left
- mx: margin-left and margin-right
- my: margin-top and margin-bottom
- p: padding
- pt: padding-top
- pr: padding-right
- pb: padding-bottom
- pl: padding-left
- px: padding-left and padding-right
- py: padding-top and padding-bottom

 We can add an alias for `pt` to become `paddingTop` for example.

**Comment by jxnblk** [comment]
Not opposed to this, but just some references for the rationale behind using shorthands like this – i.e. I believe that internalizing things like this can improve the efficiency of how you work with systems like this:

- https://interruptions.net/literature/van_Nimwegen-ICALT04-21810311.pdf
- https://getbootstrap.com/docs/4.0/utilities/spacing/
- http://tachyons.io/docs/layout/spacing/
- http://basscss.com/#basscss-margin

**Comment by hakimelek** [comment]
Interesting paper! I would definitely keep using the shorthands at this point. We can maybe add the long versions and recommend using shorthands in the docs.
