### ISSUE TITLE
InputField - Tooltip update

### ISSUE THREAD

**Issue by byrekt** [pricelinelabs/design-system#140]
Originally the design InputField had a small drawer that rendered when there was an error. An updated design changes this so that a tooltip appears attached to the (i) icon on the right side of the element.

See:
![image](https://user-images.githubusercontent.com/1385339/32784236-46bd401a-c91c-11e7-9f34-b348fdeb0969.png)

**Comment by hakimelek** [comment]
Is there a Zeplin file that we can look at? If yes, maybe we should move it to the Priceline One project.

**Comment by odmln** [comment]
@byrekt @hakimelek https://zpl.io/aB1p0RQ

**Comment by hakimelek** [comment]
#167 should address this issue!
