### ISSUE TITLE
React Warning - "Unknown prop 'theme' on <svg> tag"

### ISSUE THREAD

**Issue by BeniCheni** [pricelinelabs/design-system#160]
When visiting the `Icon` story, or any story that uses `Icon`, browser console shows a React warning about "**_Unknown prop 'theme' on <svg> tag_**":

<img width="1144" alt="screen shot 2017-11-22 at 11 21 16 pm" src="https://user-images.githubusercontent.com/6441326/33158983-c3bf02bc-cfdc-11e7-8c63-e470345a2397.png">

**Comment by hakimelek** [comment]
@BeniCheni I don't see the error https://pricelinelabs.github.io/design-system/?selectedKind=Icon&selectedStory=Icons&full=0&down=1&left=1&panelRight=0&downPanel=storybook%2Factions%2Factions-panel, Can you please reverify?

**Comment by hakimelek** [comment]
@BeniCheni  The issue is related to adding theme as a default prop to the `Icon` component. The idea behind it is to use that as a workaround for not wrapping the `ThemeProvider` around the components in the test files.  Since `Icon` does not depend on any them prop, I don't see the reason to add `theme` as a default prop anymore. So just removing that should take care of the warning.

**Comment by BeniCheni** [comment]
@hakimelek , okay. Adding `theme` to `Icon` component bloated the `Icon` test snapshot. Since there's no practical use case to add `theme` to `Icon` component, let me try out removing the `theme` as default prop in `Icon` in #161 and mention you to review the update again. Thanks for your feedback. 🙏

**Comment by BeniCheni** [comment]
@hakimelek , took your feedback to remove the `theme` of the default props of `Icon`. Please review #161 again.

**Comment by Degron** [comment]
@BeniCheni @hakimelek What if you just add theme in Icon.propTypes!

**Comment by BeniCheni** [comment]
@Degron,

My thought would agress with @hakimelek's previous feedback above that removing `theme` from `Icon` seems more viable. The use case for having theme in `Icon` is not popular enough, because of the following:

  1. Adding `theme` to `Icon` is just to help to write unit test easily without wrapping with theme provide. The tradeoff is that the `Icon` snapshot would be bloated with the `theme` addition to `Icon` source code.

  2. The `Icon` unit tests can be straight-forward without testing with theme. An icon is an SVG pretty much. The unit tests can't be complex involving `theme`, where assertion would have to do `.toHaveStyle(...)` on CSS rules.

**Comment by BeniCheni** [comment]
#161 has been merged and released to address this issue.
