### ISSUE TITLE
In <Hug> Component, if there is no icon needed, the <Text.span> wouldn't be 100% width

### ISSUE THREAD

**Issue by jinchi2013** [pricelinelabs/design-system#175]
```
   <Flex bg={bg} color={color} p={p} align="center">
      {!!icon && (
        <HideableIcon
          mr={2}
          mt="-2px"
          mb="2px"
          name={icon}
          size={24}
          display={iconDisplay}
        />
      )}
      <Text.span fontSize={fontSize}>{props.text}</Text.span>
    </Flex>
```
If there is no icon, `<Text.span>` wouldn't take 100%.  
In some case, the copy needs to be right aligned without the icon.
I think in this case just `<Text/>` would be better

@jxnblk @jes708

**Comment by jxnblk** [comment]
Yes, generally I think using the non-span version of the Text component should be preferred. Text.span is good for when you need to baseline align inline elements
