### ISSUE TITLE
Adding/standardizing animation

### ISSUE THREAD

**Issue by sqott** [pricelinelabs/design-system#198]
Would love to discuss how we could add/standardize motion/animation on different components. 

I put together a deck on the benefits of motion, some examples used in other design systems, and proposal for style, timing, and spacing standards that we can use. Link is in design-systems channel.

My idea is to: 

1. identify core transformations `(position, scale, rotation, opacity, etc.)` and assign corresponding nomenclature.
2. Create distinct timing buckets and assign them to components. For example, a large component like a modal may take 350ms to come on-screen, which would get a `transitionLarge` (or whatever we decide to name it).
3. Create 3 standard bezier curves: `easeInOut(0.50, 0.00, 0.25, 1.00)`, `easeOut(0.00, 0.00, 0.25, 1.00)`, and `easeIn(0.50, 0.00, 1.00, 1.00)` to be used based on context by an element. 

Lemme know your thoughts !

**Comment by jjmasse** [comment]
Let's also set standards for the performance of animations.
Max size, FPS, interaction FPS (ex: mobile touch and slide) etc...

**Comment by odmln** [comment]
@sqott check this out: https://github.com/drcmda/react-spring
