### ISSUE TITLE
The background: green in `<GreenButton>` got override by default blue

### ISSUE THREAD

**Issue by jinchi2013** [pricelinelabs/design-system#206]
![screen shot 2018-01-16 at 5 41 07 pm](https://user-images.githubusercontent.com/15325954/35015960-aa6fd8da-fae4-11e7-9b64-052b38826cc1.png)

Should we use `Button.extend` for this? 
@jxnblk

**Comment by jxnblk** [comment]
I would've said yes to changing to `.extend` but now it looks like they might make the current behavior work differently in a future version: https://github.com/styled-components/styled-components/issues/1546#issuecomment-367635418

Might be good to avoid using `.extend` too much IMO
