### ISSUE TITLE
Hug component issue when we don't use Icon

### ISSUE THREAD

**Issue by jinchi2013** [pricelinelabs/design-system#207]
<img width="719" alt="screen shot 2018-01-17 at 9 12 33 am" src="https://user-images.githubusercontent.com/15325954/35047190-2b85b444-fb67-11e7-8ec1-8c20e14584c1.png">
Hack to fix by
` & > div > div { width : 100% }`

**Comment by krevat** [comment]
To me this looks related to your CarAddOnHugCopy component, not the Hug; If you add the icon, it doesn't fix the problem. Your fix works, but you can also add the `width: 100%;` to the 'Add a car...' box directly (i.e. not from CarAddOnCardLayout)

I think the real fix here is to make Hug accept children so you don't have to pass in this stuff as a `text` prop.

**Comment by mattcpchen** [comment]
@jinchi2013 can you provide more details regarding how this bug happens? Cause I just test the current Hug component, and it actually can take multiple texts. Here is the quick test I put together and it works fine without any issue.
![todesignsystem](https://user-images.githubusercontent.com/11477916/37777085-221a6656-2dbd-11e8-825e-52fc4d3cc7cf.jpg)

**Comment by jxnblk** [comment]
It *seems* like this is fixed now, but feel free to reopen if not
