### ISSUE TITLE
BlockLink Component

### ISSUE THREAD

**Issue by BeniCheni** [pricelinelabs/design-system#224]
A `BlockLink` component is proposed to remove text-decoration and colors styles and sets display: block, which `BlockLink` can be used as an anchor link element as a wrapping parent to compose its block-level children components (supported by HTML 5):
```
<BlockLink href='/page'>
  <BackgroundImage image='kitten.png'>
    {/* ...etc */}
  </BackgroundImage>
</BlockLink>
```

**Comment by hakimelek** [comment]
Honestly, I don't see the reason behind having a `BlockLink` component. I feel like it's either up to the consumers of the design-system to create that for themselves or to just make this part of the `Link` component.

**Comment by BeniCheni** [comment]
@hakimelek, in several products in our team, there are a few similar use cases that use `<a>` as parent to wrap children as block-level elements, such as an image that can be clicked on and open a new browser tab with the target URL.

Such user case can be implemented using `onClick` on the `Background` image and window location `.open` API to new the tab. But since HTML 5 supports `<a>` to wrap block-level children, the previous product code review feedback suggested to simply take advantage of the HTML 5 `<a>` support and its `href` attribute, instead of implement JavaScript `onClick` event code.

Also product code review suggested to promote the `BlockLink` component to design system, since several products are using the same use case, which we're hoping to simply have a design system low-level `BlockLink` component to help out product code.

Let me know your thoughts after the highlighted use case? Hopefully this comment helps to articulate the purpose and use case of reusability of `BlockLink`.

**Comment by jxnblk** [comment]
This is a pretty common pattern, and I think it'd be better to have the CSS required to do this encapsulated in the design system, rather than having duplicative code across our code bases.

See:
- https://github.com/suitcss/utils-link/blob/master/lib/link.css#L49-L55
- https://github.com/jxnblk/rebass/blob/master/src/BlockLink.js

**Comment by hakimelek** [comment]
Fair enough ;)
