### ISSUE TITLE
Add 'autoHide` prop to Label for use in InputField component

### ISSUE THREAD

**Issue by byrekt** [pricelinelabs/design-system#226]
Currently the InputField component has a 'alwaysShowLabel' prop that determines whether the label should be there all the time. Instead we should add an optional prop to Label that looks like this:
```
<InputField>
  <Label autohide>This one shows/hides</Label>
  <Input />
</InputField>

<InputField>
  <Label>This one is always visible</Label>
  <Input />
</InputField>
```

**Comment by mattcpchen** [comment]
@byrekt Just wanna make sure I get this task right. so you want to remove this 'alwaysShowLabel' prop and use 'autohide' to do the same thing (in a reverse way)? 
Now the default behavior is not show anything unless you pass 'alwaysShowLabel'. What you want is to show label as default and if the user wanna hide it, manually pass 'autoHide'. Am I correct?

**Comment by BeniCheni** [comment]
#361 resolved this.
