### ISSUE TITLE
Add animation duration times to theme

### ISSUE THREAD

**Issue by sqott** [pricelinelabs/design-system#230]
`durationFast`  150ms
`durationNormal` 300ms
`durationSlow` 450ms
`durationSlowest` 600ms

**Comment by mattcpchen** [comment]
@sqott instead of having 4 variables, i have one called duration, so it looks like
```
duration = {
  fast: 150,
  normal: 300,
  slow: 450,
  slowest: 600
}
```
will it work for you?

**Comment by sqott** [comment]
@mattcpchen Perfect!
