### ISSUE TITLE
Find a lighter alternative to rc-slider 

### ISSUE THREAD

**Issue by hakimelek** [pricelinelabs/design-system#279]
I have noticed that the size of the design system gets significantly bigger because we have added `rc-slider` as a dependency (see graph below).

Here is a summary of some of rc-slider's dependencies with their parsed sizes:

```
└─┬ pcln-design-system@1.0.0-48 (140kb)
```
```
Slider.js (3kb)
  └─┬ rc-slider@8.6.1 (19kb)
    └─┬ rc-tooltip@3.7.0 (4kb)
      └─┬ rc-trigger@2.3.4 (15kb)
        └── rc-animate@2.4.4 (8kb)
        └── rc-align@2.3.6 (2kb)
              └── dom-align@1.6.7 (13kb)
    └─┬ rc-util@4.5.0 (5kb)
```

They add up to more than 70kb which is almost 50% the size of the entire design-system package.

<img width="624" alt="screen shot 2018-04-11 at 12 38 00 pm" src="https://user-images.githubusercontent.com/1974993/38630594-61e64fde-3d85-11e8-9a53-625ce2f1e0dd.png">

**Comment by jxnblk** [comment]
As mentioned in the original PR I also looked into this library, which claims to be 5kB:
https://github.com/sghall/react-compound-slider

**Comment by 747823** [comment]
This seems like it should be a top priority, the design system is a very heavy module to include in any front-end app now... seems like solving the tree shaking problem would help a lot with this though,

**Comment by hakimelek** [comment]
@747823 Will open a PR in a bit that exports cjs as well as es modules.

**Comment by hakimelek** [comment]
Update on this: I have a branch pushed, still making some tests on different consuming apps to make sure that everything is working as expected. Here is a link for the branch: https://github.com/pricelinelabs/design-system/tree/feat/es-build

**Comment by hakimelek** [comment]
We can close this since it got moved to a separate package in v2. We can think of a lighter version of slider in the future as well.
