### ISSUE TITLE
Button component styles do not work with `<a>` tags

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#285]
Because the Button styles are defined as heights instead of padding, using the Button as an `<a>` element (e.g. `Button.withComponent('a')`) does not style the link as expected

**Comment by odmln** [comment]
@jxnblk would adding line-heights to the different button sizes solve this?

**Comment by msafari** [comment]
thanks @odmln. You're right. We checked on doc site. Looks like this map needs to be updated to add line-height to each of them https://github.com/pricelinelabs/design-system/blob/master/src/Button.js#L10
Whoever picks this up please make sure you test it if the button had icons, ... and it still works
