### ISSUE TITLE
Remove non-custom Material Design icons

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#288]
Some of the icons in this repo are exactly the same as the default Material Design icons, and some are custom Priceline-specific icons. For non-custom icons, we should use a library like [react-icons](https://github.com/gorangajic/react-icons) instead of maintaining a copy in our repo. For backwards-compatibility, an Icon wrapping component could include a dictionary object which points to either a custom or non-custom icon based on the `name` prop

Related #240

**Comment by BeniCheni** [comment]
Morning @jxnblk, the last update of #240 was on March 2nd. Not sure if the PR would work toward to completion?

Is this v2 item something I can help out to remove the non-custom MD icons?

**Comment by BeniCheni** [comment]
Resolved by v2 release.
