### ISSUE TITLE
Add 'position' prop to Box

### ISSUE THREAD

**Issue by elizfunk** [pricelinelabs/design-system#318]
It would be nice to have a position prop for box for relative and absolute children.  Might be something good for the Card component too.

**Comment by jxnblk** [comment]
Personally, I think it's better to have separate position components since it's something that should be used with caution and can help make code a little more readable. For example, Rebass includes an Absolute component, which could be used like:

```jsx
<Absolute top={0} right={0}>
  <Card />
</Absolute>
```

**Comment by elizfunk** [comment]
Good point regarding absolute positioning.  What about relative positioning?  It could be a boolean prop on its own.

I'm thinking here only about divs that need relative positioning for their children.

**Comment by BeniCheni** [comment]
Similar to the proposed `Absolute` component, a `Relative` positive position could be "_made_" with similar supportive props to the relation position CSS rules.

If relative positions are aimed for children element, this pseudocode should demonstrate the idea in a composition with `Absolute` & `Relative` components together. Would this work for you?
```
<Absolute top={0} right={0}>
  <Relative top={5} left={5}>
    <Card />
  </Relative>
  <Relatvie bottom={10} right={10}>
    <Box />
  </Relative>
</Absolute>
```

**Comment by elizfunk** [comment]
Sounds good to me.  Should we call it `RelativeBox` and `AbsoluteBox` to make it implicit that the component has the same properties/takes the same props as the `Box` component?

Just `Absolute` and `Relative` are fine too.

Also, @jxnblk mentioned creating a `Fixed` component.
