### ISSUE TITLE
Update documentation to note when a component can take the props of other components

### ISSUE THREAD

**Issue by elizfunk** [pricelinelabs/design-system#320]
For example, the Flag component can take a width because it uses the Box component.  However, the documentation doesn't explicitly say this.  There's a code example with the width.

We should explicitly state the other props that are inherited.

**Comment by jxnblk** [comment]
I've attempted to add a note and link to the top of each component docs that shows which component it extends, e.g. https://pricelinelabs.github.io/design-system/Flex/ 

Closing this issue, but feel free to open a new one or submit a PR for any components I may have missed
