### ISSUE TITLE
Update test name for InputField to FormField

### ISSUE THREAD

**Issue by hakimelek** [pricelinelabs/design-system#329]
as per #310, InputField was generalized to FormField, we would want to rename the test from `InputField.js` to `FormField.js`.

**Comment by BeniCheni** [comment]
@hakimelek (open creator et al),

As promised in WG meeting that I'd would try some v2 issue. 😉 , I've also opened #342 to try this v2 issue. See you on the PR.

**Comment by BeniCheni** [comment]
Think this issue can be closed per the closure of related #310. We can reopen this issue if anything missed.
