### ISSUE TITLE
Fix and improve docs

### ISSUE THREAD

**Issue by hakimelek** [pricelinelabs/design-system#335]
Little things I have noticed in the docs that could be improved:

- [x] Fix live code error in `FormField`, second example. Maybe add another doc page for `InputField` to remove the confusion between the two components.
- [x] Prevent sidebar scrolling when selecting a component.
- [x] Remove comments from live code example and move them as text in markdown.
- [x] Better examples for `Box`, maybe add a background for every Box.
- [x] Better `Banner` second example, why are we showing an icon there?
- [x] Show a compound component example for Banner using Icon and Text.
- [x] Capitalize the first letter of all the descriptions in the props table.
- [x] Add a working example for `Checkbox`, could also be a recommended practice with a code snippet.
- [ ] Syntax highlighter for live code?

**Comment by hakimelek** [comment]
Let's do that.

**Comment by jxnblk** [comment]
Closing in favor of #364
