### ISSUE TITLE
Font Size Component 

### ISSUE THREAD

**Issue by jonligi** [pricelinelabs/design-system#34]
Confirm with the design team font sizes they would like. 

Possible Sizes.
10px	$font-size-x-small
12px	$font-size-small
14px	$font-size-regular
16px	$font-size-medium
18px	$font-size-large
26px	$font-size-x-large
30px	$font-size-xx-large
48px       $font-size-xxx-large

**Comment by jxnblk** [comment]
We have the `<Text />` component, which has a `fontSize` prop: https://github.com/pricelinelabs/design-system#text-

Using a number from `0–6` will pull that font-size from `theme.fontSizes` https://github.com/pricelinelabs/design-system/blob/master/src/theme.js#L26-L34

We're waiting for confirmation on the values for the typographic scale from @chrisdroukas

**Comment by hakimelek** [comment]
I think we should add those font sizes for the legacy theme for now.

**Comment by jxnblk** [comment]
Discussed this a bit in person, but will also need to update the docs.

I spoke with @chrisdroukas, and he gave me a verbal 👍 on the values that are currently in the theme.

To support legacy styles, I think the best path forward is to stick to the new typographic scale in the theme, and handle one-off font-size deviations as needed. The Text component will actually allow you to specify values beyond the theme values, e.g. `<Text fontSize={10} />` will give you 10px. If it's helpful, it might make sense to add a `<Small />` component that wraps that up more neatly in your project.

E.g.
```jsx
const Small = props => <Text fontSize={10} {...props} />
```

Closing this issue for now, but feel free to reopen if we need to discuss further
