### ISSUE TITLE
Add dark color presets to Badge

### ISSUE THREAD

**Issue by jes708** [pricelinelabs/design-system#349]
Badge does not accept dark colors as bg.  Why not?

**Comment by msafari** [comment]
also why not allow any color? Do we want to enforce those color pairings?

**Comment by wesleymartin85** [comment]
I think we should allow it to take any color. We can always write documentation to detail why white text with a lightGray background should not be done but for example if we were to add a new color to the design system we would run into this problem again.

**Comment by jes708** [comment]
That makes sense to me.  Will have a PR for this shortly.
