### ISSUE TITLE
Dropdown Component

### ISSUE THREAD

**Issue by BeniCheni** [pricelinelabs/design-system#352]
Implement `Dropdown` component, similar to [Dropdowns - Bootstrap](https://getbootstrap.com/docs/4.0/components/dropdowns/), or [Reach UI - Menu Button (Dropdown)](https://ui.reach.tech/menu-button).

**Comment by jxnblk** [comment]
Related #131

**Comment by BeniCheni** [comment]
Need to connect to pick up workstream btw @jxnblk & self to figure out the next step for this issue.

**Comment by BeniCheni** [comment]
CC @jxnblk & other WG members,

Going to pick back up this issue, any objection if the proposal for this issue uses `Dropdown` instead of ~`PopoverContainer`~ & ~`Popover`~? Feel that since the `Select` component now is pretty clear to `<select>` to wrap `<option>`, the original purpose of choosing `Popover` name to distinguish is not needed.

I'd go with `Dropdown` for the upcoming PR, if no objection. But ping me here to let me know if any thoughts.

**Comment by jxnblk** [comment]
Yeah, I think we should call this thing a `Dropdown` unless anyone has a really good reason not to

**Comment by BeniCheni** [comment]
Cross-posting [this comment from #434](https://github.com/pricelinelabs/design-system/pull/434#issuecomment-548148540) to denote why this issue could be closed. Issue could be re-opened if needed, and further question could be discussed in this thread:

> Unfortunately, after WG session, the feeling is that Select is serving most of what a Dropdown would offer. There was doubt that if reach-ui or other lib like downshift would be used. Also the underlying native <select> on mobile would opt in the mobile browser's UI & benefits for <select>.

> On that note, this undesired Dropdown PR would be closed, as well as its related issue. Further questions could be discussed in the closed issue though ...
