### ISSUE TITLE
Modal dialog component

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#372]
Consider using the [React UI Dialog](https://ui.reach.tech/dialog) component to create a standard modal for all apps cc @abautist

**Comment by jxnblk** [comment]
Notes from the meeting:
- Look into whether we want to consider the fullscreen overlay like what Flights uses

**Comment by bertya** [comment]
Seems the React UI Dialog does not have scroll lock on the background. On mobile since a lot of times the content will be longer than 1 screen. Without the lock, when user scrolls, the background moves.

**Comment by bertya** [comment]
@jxnblk tested with reach Dialog, unfortunately, it needs React 16 support. Since I don't know if we have a plan on migrating to 16, we might need to consider other options.

**Comment by sdalonzo** [comment]
@jxnblk @bertya aforementioned React 16 upgrade should land this week

**Comment by BeniCheni** [comment]
Posted an issue to ask about `style.css` in [#102 in `reach-ui`](https://github.com/reach/reach-ui/issues/102).
