### ISSUE TITLE
Namespace for Lerna Setup (@pcln/design-system?)

### ISSUE THREAD

**Issue by BeniCheni** [pricelinelabs/design-system#374]
WG session opens this PR to follow up for the [#353 Lerna setup PR comment](https://github.com/pricelinelabs/design-system/pull/353#discussion_r217876761) per name of `design-system` w. its side effect of `design-system/packages/design-system`.

CC @jxnblk, @hakimelek the origin of this topic, & anyone is welcome to chime in. Please post your thoughts in this issue to reach an agreement & potential proposed change.

**Comment by jxnblk** [comment]
To clarify, I think these are two separate issues. One is about the directory name in the repo, which has no effect on the npm package name. The other part of the discussion is about using a package scope (`@pcln`), which we should discuss in the next meeting

**Comment by jxnblk** [comment]
Going to close this out since we discussed in the meeting. As of now, there's no plan to introduce an npm scope to the open source packages
