### ISSUE TITLE
Should imported Icons be removed from the core package?

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#375]

**Comment by jxnblk** [comment]
After a quick glance, it looks like the following components import the current Icon component:
- Hug
- CloseButton
- IconButton
- Select
- Radio
- Checkbox
- Banner
- FormField

- The FormField will not require the Icon import with the changes in #361 
- Because the CloseButton, Select, Radio, and Checkbox components import specific icons, they do not require the entire icon library, and can be updated to import the icons individually.
- The IconButton component, could be included in the new pcln-icons package, instead of the core design system package
- The Hug and Banner component APIs could be updated to be more composable and not import the Icon component directly

Since completely removing the Icon component would require updates to all these components and increase the scope for migration, I'd suggest postponing the complete removal until after v2 is out and slating the change for a smaller v3 to follow later, but open to hearing thoughts from the team

**Comment by BeniCheni** [comment]
Resolved by v2 release.
