### ISSUE TITLE
Adjust ipad breakpoint in new RC drive search app

### ISSUE THREAD

**Issue by wmdzign** [pricelinelabs/design-system#379]
Currently in the new RC drive search app https://www.priceline.com/drive/search/r the ipad breakpoint is happening at 767 instead of 768. Can we adjust to break at 768?

**Comment by jxnblk** [comment]
The design system uses `48em` as a breakpoint, but afaik RC has some custom breakpoints. You can use the `customBreakpoints` prop in the `ThemeProvider` to set them however you need in the app

**Comment by jxnblk** [comment]
Closing this out because this needs more context
