### ISSUE TITLE
Contributing Guide Link On README => 404

### ISSUE THREAD

**Issue by BeniCheni** [pricelinelabs/design-system#390]
The [Contributing guide](https://github.com/pricelinelabs/design-system/blob/master/docs/Contributing.md) on the README is pointing to 404 GH page.

Where should it go?

**Comment by jxnblk** [comment]
https://github.com/pricelinelabs/design-system/blob/master/docs/pages/Contributing.md

**Comment by jxnblk** [comment]
Though, we might want to move this doc to the root and follow the `CONTRIBUTING.md` convention

**Comment by BeniCheni** [comment]
Thanks for contributing to fix this issue, @bertya.
