### ISSUE TITLE
Text link to Github doc broken

### ISSUE THREAD

**Issue by BryanEdison** [pricelinelabs/design-system#392]
The "Text" link on the Text Doc is broken to link to a 404 page. Would need someone to update the link on the Text doc.

Link is on the Heading page at: https://pricelinelabs.github.io/design-system/Heading/

Currently links to: https://pricelinelabs.github.io/Text

Valid working link is: https://pricelinelabs.github.io/design-system/Text/

**Comment by jxnblk** [comment]
Related to #386

**Comment by jxnblk** [comment]
Closing this in favor of tracking in #363
