### ISSUE TITLE
Error "keyframe declaration" on 2.0.6

### ISSUE THREAD

**Issue by efd1** [pricelinelabs/design-system#415]
I've got an error with the beta version 2.0.6: 

"**Uncaught Error: It seems you are interpolating a keyframe declaration (eMLfYp) into an untagged string. This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand. Please wrap your string in the css\`\` helper (see https://www.styled-components.com/docs/api#css), which ensures the styles are injected correctly.**"
![image](https://user-images.githubusercontent.com/7147919/48645061-c9aa5a00-e9e4-11e8-8d2c-6d75530b04de.png)

It seems that the `labelStyles` object needs to be replaced by a css`` here (I'm not sure): https://github.com/pricelinelabs/design-system/blob/next/packages/core/src/FormField.js#L27

Links to the docs:
https://www.styled-components.com/docs/api#keyframes
https://www.styled-components.com/docs/api#css

**Comment by jxnblk** [comment]
Should be fixed with #361

**Comment by jxnblk** [comment]
This *should* be fixed now, but feel free to reopen if you're still seeing this issue

**Comment by efd1** [comment]
Yes it's working! Thank you! 😀🎉
