### ISSUE TITLE
Existing Design Systems for inspiration

### ISSUE THREAD

**Issue by hakimelek** [pricelinelabs/design-system#42]
This is a list of design systems we found interesting, mainly built with React:

- [Atlas kit](https://atlaskit.atlassian.com/) - Atlassian
- [Blueprint](http://blueprintjs.com/) - Palantir
- [Polaris](https://polaris.shopify.com/) - Shopify
- [Lightning Design System](https://www.lightningdesignsystem.com/) - Salesforce
- ..

Also there is a great list of [awesome design systems](https://github.com/alexpate/awesome-design-systems) worth checking out.

**Comment by jxnblk** [comment]
We could add a docs file to start collecting things like inspiration/articles/etc. I'd like to add a `docs/` folder to better organize what's currently in the readme and have a place for more docs to live in the future

**Comment by chrisdroukas** [comment]
Would the wiki be a suitable place for this sort of thing?

**Comment by hakimelek** [comment]
@chrisdroukas indeed! We can move that to a wiki page once we have more content.

**Comment by hakimelek** [comment]
* [Lightning Design System](https://www.lightningdesignsystem.com/) - Salesforce

**Comment by jxnblk** [comment]
Closing in preference of adding some links to the docs site
