### ISSUE TITLE
Rollup warns "Mixing named and default exports" when bundling slider package?

### ISSUE THREAD

**Issue by BeniCheni** [pricelinelabs/design-system#440]
When `npm run prepare` is running w. `rollup` to bundle the slider package, the log warns the mixing named & default exports. Can this be debugged to understand more?

```sh
> pcln-slider@2.0.0-beta.7 prepare /design-system/packages/slider
> rollup --config


src/index.js → dist/index.cjs.js, dist/index.esm.js...
(!) Mixing named and default exports
Consumers of your bundle will have to use bundle['default'] to access the default export, which may not be what you want. Use `output.exports: 'named'` to disable this warning
```

**Comment by muuvmuuv** [comment]
I got the same issue, how should I handle this?

**Comment by BeniCheni** [comment]
Suspecting that the namespaces between `index.cjs.js` and `index.esm.js` are sharing "index" to trigger the mixed named and default exports.

It may be worth of a try w. `index-cjs.js` and `index-esm.js` update, and validate again to see if warnings are still happening in `npm run prepare`.

Would you like to try it out and open a PR to help out if it works out in your local? @muuvmuuv 

(cc/ some WG to notify about this thread of roll-up warning: @bertya / @sdalonzo / @dansternfeld1

**Comment by BeniCheni** [comment]
2nd thought would be to try out `.mjs` extensive for es module.

**Comment by BeniCheni** [comment]
Just did a dry-run, and was able to verify that the reported issue is no longer observed. Closing the issue now. Can re-open if there's further observation.
