### ISSUE TITLE
Maintain, automate or deprecate CHANGELOG.md?

### ISSUE THREAD

**Issue by BeniCheni** [pricelinelabs/design-system#452]
#449 is adding to `CHANGELOG.md` to track the the added feature, which I think it's an example of a "_clean_" PR and a nice benefit to adapt change log. However, our previous publishes did not use change log.

I'd think it's a simple follow-up topic to quickly discuss the consensus to either maintain, or automate, or deprecate `CHANGELOG.md`.

**Comment by dansternfeld1** [comment]
Talking about it in the room, we're thinking that the releases tab contains the needed release notes:
https://github.com/pricelinelabs/design-system/releases

I think we're leaning toward "Deprecate" for CHANGELOG.md

**Comment by BeniCheni** [comment]
Glad to hear back consensus, @dansternfeld1. I've labeled this issue "_help wanted_" and "_good first issue_" for a volunteer to open a simple PR to delete the `CHANGELOG.md` file.

**Comment by BeniCheni** [comment]
@dansternfeld1 et al, opened #456 to address this issue.
