### ISSUE TITLE
doc site uses DS v1

### ISSUE THREAD

**Issue by jes708** [pricelinelabs/design-system#480]
Our docs site still has v1 colors and does not recognize v2 props in the live code examples.  Let's update the docs site to use DS v2.

https://pricelinelabs.github.io/design-system/color/

**Comment by jes708** [comment]
Previous attempt to simply update package.json in docs folder did not work.  I think we're going to have to run `npm run build` on the docs and then put that in the `gh-pages` branch or start using `master/docs` as our new host for the docs site.  The latter should be acceptable now, as this won't inflate the size of pcln-design-system thanks to our monorepo setup.

**Comment by unscsprt** [comment]
Confirmed that this issue has been resolved. Docs site currently uses DS v2.0.5
