### ISSUE TITLE
Add new lightOrange back into v2 theme.js

### ISSUE THREAD

**Issue by wesleymartin85** [pricelinelabs/design-system#485]
Use hex: FEF2E7 and add lightOrange to theme.js @jes708 after you add this color we could probably close issues #481 and #480 ?

**Comment by jes708** [comment]
#481 yes, #480 is a different issue, wherein we need to update our doc site to show v2 colors instead of v1 colors.

**Comment by wesleymartin85** [comment]
@jes708  for the lightOrange we would need to update the deprecated aliases to remove orange

`// deprecated aliases
const darkPurple = purple
const lightOrange = orange`

`const colors = {
  // deprecated
  lightOrange,
  darkPurple
}`

**Comment by jes708** [comment]
That is taken care of in #483
