### ISSUE TITLE
Can pcln-modal support styled-components v2?

### ISSUE THREAD

**Issue by jes708** [pricelinelabs/design-system#492]
Would it be difficult to add support for styled-components v2 to pcln-modal?  Host apps with SC v2 see error:` Cannot create styled-components for component: [object Object] at constructWithOptions`

**Comment by sdalonzo** [comment]
@bertya any thoughts?

**Comment by jes708** [comment]
SC v3 is relatively easy to upgrade to so I'll close this issue
