### ISSUE TITLE
Increase default fontSize to 16px for Input

### ISSUE THREAD

**Issue by jes708** [pricelinelabs/design-system#521]
Mobile browsers will zoom in on any `<Input>` selected that has a fontSize <16px.  This can lead to undesirable and confusing zooming that the user will have to counteract if the input also brings up an accompanying overlay when selected. To prevent this behavior, and the urge to disable zooming with custom meta viewport tags, should default `<Input>` fontSize be 16px instead of 14px?

**Comment by wesleymartin85** [comment]
@jes708 @dansternfeld1 here is a working documentation guide for the input component. At the bottom under the behavior section you will see the guidelines for mobile styles. 

https://priceline.invisionapp.com/share/BGTOVWY2F87

Let me know if you have any questions.

**Comment by jes708** [comment]
I'll get started on this.
