### ISSUE TITLE
InlineBlock Component

### ISSUE THREAD

**Issue by BeniCheni** [pricelinelabs/design-system#53]
The proposed `<InlineBlockBox />` component is a type of`<Box />` component with inline-block display.

**Comment by jxnblk** [comment]
I would opt to simplify the name to InlineBlock, a la https://github.com/smyte/jsxstyle

An alternative would be a display prop on the Box component, but think the readability of a separate component would be better

**Comment by hakimelek** [comment]
Are we using this a lot?

**Comment by BeniCheni** [comment]
Closing as this original idea is no longer in scope.
