### ISSUE TITLE
Badge component should be more configurable

### ISSUE THREAD

**Issue by unscsprt** [pricelinelabs/design-system#533]
# Use case:
We'd like to be able to configure `Badge` to look similar to `Stamp`.

## Example:
<img width="127" alt="Screen Shot 2019-07-12 at 8 56 08 AM" src="https://user-images.githubusercontent.com/3260642/61129695-f256f680-a482-11e9-8c77-42c8fa7391f1.png">

# Proposed props:
- `borderRadius` (string or bool) - Either standard CSS `border-radius` rule, or a `bool` to use a Stamp-like border-radius.
- `fontSize` (string) - Same typography scale as used for `<Text>`

**Comment by dansternfeld1** [comment]
Discussion in the room seems to favor changing Stamp to allow setting of border-color for this use case

Other thoughts?
