### ISSUE TITLE
Image height attribute does not have precedence

### ISSUE THREAD

**Issue by jes708** [pricelinelabs/design-system#556]
`<Image height='60' />` does not work since `height: auto` is specified as a style rule.  Perhaps this predefined height should be set using styled-components' `.attrs` method instead.

**Comment by dansternfeld1** [comment]
https://github.com/pricelinelabs/design-system/blob/c2ad5c588944d5713bb6c61f32ce20a81368d31b/packages/core/src/Image.js#L7

**Comment by BeniCheni** [comment]
Added @suyashchopra19 as an assignee, since he's interested in helping this issue out.

**Comment by suyashchopra19** [comment]
This issue has been resolved with #592
