### ISSUE TITLE
Truncate component

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#58]
An extension to the Text component that sets the following styles:

```css
  overflow: hidden;
  whiteSpace: nowrap;
  textOverflow: ellipsis;
```

**Comment by dansternfeld1** [comment]
It should probably require a `width` property

**Comment by jxnblk** [comment]
You can control width with the container it's in, but adding a `width` prop would only require using styled-system like in the Box component

e.g.
```jsx
<Box width={1/2}>
  <Truncate children={someString} />
</Box>
```

**Comment by BeniCheni** [comment]
FYI I'd pick up this issue, since I have similar truncation in styles in a client app that uses the `pcln-design-sysem`.

**Comment by BeniCheni** [comment]
Closing this issue as the Truncate component has been implemented, reviewed, merged and released.
