### ISSUE TITLE
Close icon in light banners should not change color on hover

### ISSUE THREAD

**Issue by abautist** [pricelinelabs/design-system#594]
On hover of the close button in banners with light background colors the color changes to white making the icon difficult to see.

<img width="1572" alt="Screen Shot 2019-09-24 at 5 10 33 PM" src="https://user-images.githubusercontent.com/5533800/65606179-68de9d00-df78-11e9-948c-7a5eba65d7b8.png">

The icon should not change color and remain the same color as the text even on hover.

**Comment by BeniCheni** [comment]
Think this bit of hover style code of `Button` needs to be adjusted:

https://github.com/pricelinelabs/design-system/blob/34452f645c9439fb0261cce91fa4306b74fba72e/packages/core/src/Button.js#L44-L49

**Comment by achoboter** [comment]
@BeniCheni nah I think all that's needed is a `color: inherit;` in the hover of:

https://github.com/pricelinelabs/design-system/blob/34452f645c9439fb0261cce91fa4306b74fba72e/packages/core/src/IconButton.js#L7-L18

**Comment by achoboter** [comment]
@abautist fix PR https://github.com/pricelinelabs/design-system/pull/595

**Comment by BeniCheni** [comment]
Landed the fix in #595
