### ISSUE TITLE
Card component

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#65]
An extension of the Box component that includes a border/box-shadow style. This would also include adding @odmln's shadows to the theme

**Comment by odmln** [comment]
`
.shadowSm {
  box-shadow: 
    0 0 4px 0 rgba(0,0,0,0.08);
}
.shadowMd {
  box-shadow: 
    0 0 4px 0 rgba(0,0,0,0.08),
    0 8px 8px 0 rgba(0,0,0,0.08);
}
.shadowLg {
  box-shadow: 
    0 0 4px 0 rgba(0,0,0,0.08),
    0 8px 8px 0 rgba(0,0,0,0.08),
    0 16px 16px 0 rgba(0,0,0,0.08);
}
.shadowXl {
  box-shadow: 
    0 0 4px 0 rgba(0,0,0,0.08),
    0 8px 8px 0 rgba(0,0,0,0.08),
    0 16px 16px 0 rgba(0,0,0,0.08),
    0 32px 32px 0 rgba(0,0,0,0.08);
}
`

Link to Zeplin for visuals : https://zpl.io/2ykve7y

**Comment by hakimelek** [comment]
#100
