### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#71]

**Comment by hakimelek** [comment]
Zeplin mocks reference: https://app.zeplin.io/project/596d11bc29e9db6303116850/screen/59ce7dfd95b559f689da4ff2

**Comment by BeniCheni** [comment]
Trying out `Select` & `SelectField` elements.

**Comment by BeniCheni** [comment]
I will work with Dom Gautier to write the `Select` component first for the immediate project need, then we will iterate the `Dropdown` components as a follow-up next.
