### ISSUE TITLE
Add new Icons

### ISSUE THREAD

**Issue by hakimelek** [pricelinelabs/design-system#88]

**Comment by odmln** [comment]
Via [this link](https://github.com/pricelinelabs/design-system-sketch/tree/master/assets) you can find roughly 70+ SVG icons. They are organized by icon type (action, alert, communication, search, etc). Feel free to create an issue in the [design-system-sketch](https://github.com/pricelinelabs/design-system-sketch) repo if you need any new ones created.

**Comment by jxnblk** [comment]
We're working on migrating the SVGs to this repo, WIP branch here https://github.com/pricelinelabs/design-system/tree/new-md-icons

**Comment by hakimelek** [comment]
Should be addressed in #135
