### ISSUE TITLE
Alert component

### ISSUE THREAD

**Issue by jxnblk** [pricelinelabs/design-system#90]
Per https://app.zeplin.io/project/596d11bc29e9db6303116850/screen/59ce7dfc54b85ec584d3df7e

Could be composed of the Flex, Text, and Icon components

**Comment by Emuentes** [comment]
@jxnblk, how do I get invited to that Zeplin project?

**Comment by chrisdroukas** [comment]
@Emuentes added!

**Comment by Emuentes** [comment]
@chrisdroukas Thanks, brotha.

**Comment by jxnblk** [comment]
Now called the **Banner** and in PR #111
